GET http://localhost:3000/user-api/
###
GET http://localhost:3000/author-api/
###
GET http://localhost:3000/admin-api/

###Create user
POST http://localhost:3000/user-api/users
Content-Type: application/json

{
    "name": "Sahasra",
    "email": "sahasra@gmail.com",
    "password": "Sahasra@123",
    "role": "user"
}
## create author
POST http://localhost:3000/author-api/users
Content-Type: application/json

{
    "name": "John Author",
    "email": "author@gmail.com",
    "password": "Author@123",
    "role": "author"
}
### POST Article
POST http://localhost:3000/author-api/article
Content-Type: application/json

{
    "authorData": {
        "nameOfAuthor": "John Author",
        "email": "author@gmail.com",
        "profileImageUrl": "https://example.com/profile.jpg"
    },
    "articleId": "{{$timestamp}}",
    "title": "Introduction to MERN Stack",
    "category": "Web Development",
    "content": "MERN stack is a popular technology stack consisting of MongoDB, Express.js, React.js and Node.js. It is used to build full-stack web applications.",
    "dateOfCreation": "{{$datetime iso8601}}",
    "dateOfModification": "{{$datetime iso8601}}",
    "comments": [],
    "isArticleActive": true
}

### MODIFY Article
PUT http://localhost:3000/author-api/article/6a7c451e37c44e6b8c150235
Content-Type: application/json

{
    "authorData": {
        "nameOfAuthor": "John Author",
        "email": "author@gmail.com",
        "profileImageUrl": "https://example.com/profile.jpg"
    },
    "title": "Introduction to MERN",
    "category": "Web Dev",
    "content": "MERN stack is a popular technology stack consisting of MongoDB, Express.js, React.js and Node.js. It is used to build full-stack web applications.",
    "dateOfModification": "{{$datetime iso8601}}",
    "comments": [],
    "isArticleActive": true
}